from PyQt5 import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 620)
        MainWindow.setMinimumSize(QtCore.QSize(400, 620))
        MainWindow.setMaximumSize(QtCore.QSize(400, 620))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushbutton_8 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("8"))
        self.pushbutton_8.setGeometry(QtCore.QRect(130, 130, 75, 75))
        self.pushbutton_8.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_8.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_8.setFont(font)
        self.pushbutton_8.setObjectName("pushbutton_8")
        self.output_box = QtWidgets.QLabel(self.centralwidget)
        self.output_box.setGeometry(QtCore.QRect(34, 45, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(20)
        self.output_box.setFont(font)
        self.output_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.output_box.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_box.setObjectName("output_box")
        self.pushbutton_7 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("7"))
        self.pushbutton_7.setGeometry(QtCore.QRect(50, 130, 75, 75))
        self.pushbutton_7.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_7.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_7.setFont(font)
        self.pushbutton_7.setObjectName("pushbutton_7")
        self.pushbutton_9 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("9"))
        self.pushbutton_9.setGeometry(QtCore.QRect(210, 130, 75, 75))
        self.pushbutton_9.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_9.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_9.setFont(font)
        self.pushbutton_9.setObjectName("pushbutton_9")
        self.pushbutton_4 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("4"))
        self.pushbutton_4.setGeometry(QtCore.QRect(50, 210, 75, 75))
        self.pushbutton_4.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_4.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushbutton_4.setFont(font)
        self.pushbutton_4.setObjectName("pushbutton_4")
        self.pushbutton_5 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("5"))
        self.pushbutton_5.setGeometry(QtCore.QRect(130, 210, 75, 75))
        self.pushbutton_5.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_5.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_5.setFont(font)
        self.pushbutton_5.setObjectName("pushbutton_5")
        self.pushbutton_6 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("6"))
        self.pushbutton_6.setGeometry(QtCore.QRect(210, 210, 75, 75))
        self.pushbutton_6.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_6.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_6.setFont(font)
        self.pushbutton_6.setObjectName("pushbutton_6")
        self.pushbutton_1 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("1"))
        self.pushbutton_1.setGeometry(QtCore.QRect(50, 290, 75, 75))
        self.pushbutton_1.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_1.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_1.setFont(font)
        self.pushbutton_1.setObjectName("pushbutton_1")
        self.pushbutton_2 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("2"))
        self.pushbutton_2.setGeometry(QtCore.QRect(130, 290, 75, 75))
        self.pushbutton_2.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_2.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_2.setFont(font)
        self.pushbutton_2.setObjectName("pushbutton_2")
        self.pushbutton_3 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("3"))
        self.pushbutton_3.setGeometry(QtCore.QRect(210, 290, 75, 75))
        self.pushbutton_3.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_3.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_3.setFont(font)
        self.pushbutton_3.setObjectName("pushbutton_3")
        self.pushbutton_decimal = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.decimal())
        self.pushbutton_decimal.setGeometry(QtCore.QRect(50, 370, 75, 75))
        self.pushbutton_decimal.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_decimal.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushbutton_decimal.setFont(font)
        self.pushbutton_decimal.setObjectName("pushbutton_decimal")
        self.pushbutton_power = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.power())
        self.pushbutton_power.setGeometry(QtCore.QRect(210, 370, 75, 75))
        self.pushbutton_power.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_power.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_power.setFont(font)
        self.pushbutton_power.setObjectName("pushbutton_power")
        self.pushbutton_subtract = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.subtract())
        self.pushbutton_subtract.setGeometry(QtCore.QRect(300, 210, 75, 75))
        self.pushbutton_subtract.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_subtract.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_subtract.setFont(font)
        self.pushbutton_subtract.setObjectName("pushbutton_subtract")
        self.pushbutton_multiply = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.multiply())
        self.pushbutton_multiply.setGeometry(QtCore.QRect(300, 290, 75, 75))
        self.pushbutton_multiply.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_multiply.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_multiply.setFont(font)
        self.pushbutton_multiply.setObjectName("pushbutton_multiply")
        self.pushbutton_0 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.pressed("0"))
        self.pushbutton_0.setGeometry(QtCore.QRect(130, 370, 75, 75))
        self.pushbutton_0.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_0.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_0.setFont(font)
        self.pushbutton_0.setObjectName("pushbutton_0")
        self.pushbutton_add = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.add())
        self.pushbutton_add.setGeometry(QtCore.QRect(300, 130, 75, 75))
        self.pushbutton_add.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_add.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_add.setFont(font)
        self.pushbutton_add.setObjectName("pushbutton_add")
        self.pushbutton_divide = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.divide())
        self.pushbutton_divide.setGeometry(QtCore.QRect(300, 370, 75, 75))
        self.pushbutton_divide.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_divide.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_divide.setFont(font)
        self.pushbutton_divide.setObjectName("pushbutton_divide")
        self.pushbutton_enter = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.enter())
        self.pushbutton_enter.setGeometry(QtCore.QRect(215, 520, 160, 60))
        self.pushbutton_enter.setMinimumSize(QtCore.QSize(160, 60))
        self.pushbutton_enter.setMaximumSize(QtCore.QSize(325, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_enter.setFont(font)
        self.pushbutton_enter.setObjectName("pushbutton_enter")
        self.pushbutton_clear = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.clear())
        self.pushbutton_clear.setGeometry(QtCore.QRect(215, 450, 160, 60))
        self.pushbutton_clear.setMinimumSize(QtCore.QSize(160, 60))
        self.pushbutton_clear.setMaximumSize(QtCore.QSize(325, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushbutton_clear.setFont(font)
        self.pushbutton_clear.setObjectName("pushbutton_clear")
        self.pushbutton_flipsign = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.flipsign())
        self.pushbutton_flipsign.setGeometry(QtCore.QRect(50, 450, 75, 75))
        self.pushbutton_flipsign.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_flipsign.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushbutton_flipsign.setFont(font)
        self.pushbutton_flipsign.setObjectName("pushbutton_flipsign")
        self.pushbutton_delete = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.delete())
        self.pushbutton_delete.setGeometry(QtCore.QRect(130, 450, 75, 75))
        self.pushbutton_delete.setMinimumSize(QtCore.QSize(75, 75))
        self.pushbutton_delete.setMaximumSize(QtCore.QSize(75, 75))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.pushbutton_delete.setFont(font)
        self.pushbutton_delete.setObjectName("pushbutton_delete")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ProjectPart1"))
        self.pushbutton_8.setText(_translate("MainWindow", "8"))
        self.output_box.setText(_translate("MainWindow", "0"))
        self.pushbutton_7.setText(_translate("MainWindow", "7"))
        self.pushbutton_9.setText(_translate("MainWindow", "9"))
        self.pushbutton_4.setText(_translate("MainWindow", "4"))
        self.pushbutton_5.setText(_translate("MainWindow", "5"))
        self.pushbutton_6.setText(_translate("MainWindow", "6"))
        self.pushbutton_1.setText(_translate("MainWindow", "1"))
        self.pushbutton_2.setText(_translate("MainWindow", "2"))
        self.pushbutton_3.setText(_translate("MainWindow", "3"))
        self.pushbutton_decimal.setText(_translate("MainWindow", "."))
        self.pushbutton_power.setText(_translate("MainWindow", "x^y"))
        self.pushbutton_subtract.setText(_translate("MainWindow", "-"))
        self.pushbutton_multiply.setText(_translate("MainWindow", "*"))
        self.pushbutton_0.setText(_translate("MainWindow", "0"))
        self.pushbutton_add.setText(_translate("MainWindow", "+"))
        self.pushbutton_divide.setText(_translate("MainWindow", "/"))
        self.pushbutton_enter.setText(_translate("MainWindow", "Enter"))
        self.pushbutton_clear.setText(_translate("MainWindow", "Clear"))
        self.pushbutton_flipsign.setText(_translate("MainWindow", "+/-"))
        self.pushbutton_delete.setText(_translate("MainWindow", "<<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
